### ISSUE TITLE
typo: splitslines in L should change to splitlines 

### ISSUE THREAD

**Issue by sky1ove** [AnswerDotAI/fastcore#655]
in 
```
@classmethod
def splitlines(cls, s, keepends=False): return cls(s.splitslines(keepends))
```

s.splitslines should change to s.splitlines

**Comment by audreyfeldroy** [comment]
Hi @sky1ove, this is fixed in fastcore 1.7.26: https://github.com/AnswerDotAI/fastcore/blob/main/CHANGELOG.md?plain=1#L17
